version: 2
updates:
  - package-ecosystem: gradle
    directory: "app"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
