/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Path;

import org.eclipse.jgit.api.Git;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import org.tinylog.Logger;

import static org.junit.jupiter.api.Assertions.assertTrue;

class JGitTest {

    private @TempDir Path repoDir;

    @Test
    public void testCloneRepository() throws Exception {
        Git git = Git.cloneRepository()
                     .setURI("https://github.com/JabRef/jabref.git")
                     .setDirectory(repoDir.toFile())
                     .call();
        git.close();
        Logger.info("Cloned repository to {}", repoDir);
        assertTrue(Files.exists(repoDir));
    }
}
