/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Path;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.tinylog.Logger;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class JGitTest {

    private @TempDir Path repoDir;

    @Test
    public void testCloneRepository() throws Exception {
        try (Git git = Git.cloneRepository()
                          .setURI("https://github.com/koppor/jgit-mwe.git")
                          .setDirectory(repoDir.toFile())
                          .call()) {
            Logger.info("Cloned repository to {}", repoDir);
        }
    }

    @Test
    public void testClonePrivateRepository() throws Exception {
        String username = System.getenv("GH_USERNAME");
        assertNotNull(username);

        String password = System.getenv("GH_PAT");
        assertNotNull(password);

        UsernamePasswordCredentialsProvider usernamePasswordCredentialsProvider = new UsernamePasswordCredentialsProvider(username, password);
        try (Git git = Git.cloneRepository()
                          .setURI("https://github.com/koppor/jgit-mwe-private-repo.git")
                          .setDirectory(repoDir.toFile())
                          .setCredentialsProvider(usernamePasswordCredentialsProvider)
                          .call()) {
            Logger.info("Cloned repository to {}", repoDir);
        }
    }
}
